### ISSUE TITLE
🌟 [feat] 카페 페이지 전체 조회(일반 유저)

### ISSUE THREAD

**Issue by seungsuuu** [LeeChangHyeong/CoffeeDeliveryProject#50]
**🌟 Issue : Feature**
일반 유저의 카페 페이지 전체 조회 기능 구현

**Description**
일반 유저 클라이언트의 요청으로 DB에 저장된 전체 카페 페이지를 보여주는 기능입니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] UserContoller, UserSevice 클래스 생성
- [x] UserContoller에 getAllCafe API 구현
- [x] UserService에 getAllCafe 메서드 로직 구현

**Reference(Optional)**

Admin이 아닌 일반 유저의 카페 페이지 전체 조회입니다.
